language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install python-coveralls
script:
  - coverage run manage.py test
after_success:
  - coverage report
  - coveralls
