language: python
python:
  - "3.4"
branches:
  only:
    - master
    - v0.2-devel
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install python-coveralls
script:
  - coverage run manage.py test
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
after_failure:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ab59686b416ffab52cb9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
