language: python
python:
  - "3.4"
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install python-coveralls
script:
  - coverage run manage.py test
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
after_failure:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
